### ISSUE TITLE
Ef Migrations Issue

### ISSUE THREAD

**Issue by DaleCam** [havit/NewProjectTemplate-Blazor#1]
Hello! First of all thank you soo much for this template! 
I just had one issue that im stuck on. I ran your steps in the readme and I got to the step:
Add new initial migration `Add-Migration Initial -StartupProject Entity.Tests`

However I get the following errors. If i run it against the Entity.Tests folder i get the error:
No DbContext was found in assembly 'Blazor.Learning.Entity.Tests'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic

and if i run "Add new initial migration `Add-Migration Initial -StartupProject Entity" (without the .Tests becasue i thought that was wierd) i get the error:
Could not load assembly 'Blazor.Learning.Entity.Tests'. Ensure it is referenced by the startup project 'IWS.TradeStats.Entity'

Any ideas would be greatly appreciated!
Thank you!

FWIW i will happily update the readme if we find a step that is missed or needs adjusting :)

**Comment by DaleCam** [comment]
Ok I solved it - forgot one step. In the Package Manager console I had to select server\Entity as the default project in its IDE. Please let me know if you would like me to add that step to your readme.
Thanks again!

**Comment by hakenr** [comment]
@DaleCam First of all, let me say you are super brave you decided to use our enterprise template as there is literally no documentation and by now all the known usages of the template are our commercial projects (for our customers) or side projects of our own employees or near friends. We have recorded several videos for onboarding the stack for our new employees and we have quite a large internal documentation, but unfortunately everything is in Czech language.

For now - I really appreciate your determination to use the template - so don't hesitate to use the Issues here to ask questions you might have and we will try to help you move forward.

If you want to try luck with Google Translator, you will find the PDF dump of our internal documentation (relevant parts) here: https://github.com/mensagymnazium/IntranetGen3/tree/master/doc/HAVIT%20Stack

First thing to emphasize - execute the `Run-CodeGenerator.ps1` in DataLayer after every single Model change. It will generate the repositories and other DataLayer stuff for you.

**Comment by DaleCam** [comment]
Thanks so much @hakenr ! Its very generous what you are sharing, and i really appreciate it!
